### ISSUE TITLE
add info Mathijs

### ISSUE THREAD

**Issue by imme-emosol** [mediatechnologie/gamehub#2]
please add info about what your contribution to this project will be at the following uri:
https://github.com/mediatechnologie/gamehub/wiki/Mathijs .

**Comment by mbernson** [comment]
Voilá.

**Comment by imme-emosol** [comment]
nope, you're doing it wrong.

from the list of games, please select some of the games that you might find interesting to code and put it on this page.

besides that please provide your personal skill-set and what you would like to do and learn in this project.

**Comment by mbernson** [comment]
I have added some additional information.
